# .readthedocs.yaml

# Declare the version of the Read the Docs configuration schema
version: 3

# Define the build environment and settings
sphinx:
  configuration: docs/source/conf.py
  python:
    version: 3.10
    install:
      - requirements: requirements.txt
    system_packages: true



